name: Xcode - Build, Test, and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build, Test, and Analyze Framework
    runs-on: macos-latest

    strategy:
      matrix:
        platform: [ios, macos]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: |
          sudo xcode-select -s /Applications/Xcode.app

      - name: Determine Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo "scheme=$default" >> $GITHUB_ENV
          echo "Using scheme: $default"

      - name: Build and Analyze
        run: |
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then 
            filetype_parameter="workspace"
            file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
          else 
            filetype_parameter="project"
            file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`

          if [ "${{ matrix.platform }}" = "ios" ]; then
            destination="platform=iOS Simulator,name=iPhone 15,OS=latest"
          else
            destination="platform=macOS"
          fi

          xcodebuild clean build analyze \
            -scheme "$scheme" \
            -"$filetype_parameter" "$file_to_build" \
            -destination "$destination" | xcpretty && exit ${PIPESTATUS[0]}

      - name: Run Unit Tests
        run: |
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then 
            filetype_parameter="workspace"
            file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
          else 
            filetype_parameter="project"
            file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`

          if [ "${{ matrix.platform }}" = "ios" ]; then
            destination="platform=iOS Simulator,name=iPhone 15,OS=latest"
          else
            destination="platform=macOS"
          fi

          xcodebuild test \
            -scheme "$scheme" \
            -"$filetype_parameter" "$file_to_build" \
            -destination "$destination" | xcpretty && exit ${PIPESTATUS[0]}
